name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: compile
      run: g++ -Wall -std=c++17 test.cpp -o test
    - name: check
      run: ./test -s
